[project]
name = "sspython"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "mat73>=0.65",
    "mne>=1.11.0",
    "mne-icalabel>=0.8.1",
    "mne-lsl>=1.13.0",
    "mne-qt-browser>=0.7.4",
    "pyqtgraph>=0.14.0",
    "pyopengl>=3.1.10",
    "pyside6>=6.10.2",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "statsmodels>=0.14.6",
    "torch>=2.11.0",
    "nuitka>=4.0.7",
    "setuptools>=81.0.0",
    "wheel>=0.46.3",
    "ordered-set>=4.1.0",
    "zstandard>=0.25.0",
    "imageio>=2.37.3",
]
