[build-system]
requires = ["setuptools>=81.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sspython"
dynamic = ["version"]
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "mat73>=0.65",
    "mne>=1.11.0",
    "mne-icalabel>=0.8.1",
    "mne-lsl>=1.13.0",
    "mne-qt-browser>=0.7.4",
    "pyqtgraph>=0.14.0",
    "pyopengl>=3.1.10",
    "pyside6>=6.10.2",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "statsmodels>=0.14.6",
    "torch>=2.11.0",
    "imageio>=2.37.3",
    "h5io>=0.2.5",
    "pyvistaqt>=0.12.0",
    "nibabel>=5.4.2",
]

[dependency-groups]
build = [
    "pyinstaller>=6.21.0",
    "pyinstaller-hooks-contrib>=2026.6",
]
dev = [
    "jupyter>=1.1.1",
]

[tool.setuptools]
py-modules = ["main", "utils"]
include-package-data = false

[tool.setuptools.dynamic]
version = { attr = "core.version.__version__" }

[tool.setuptools.packages.find]
where = ["."]
include = ["core*", "ui*"]
namespaces = true
